# Generated by Django 5.0 on 2023-12-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karier_terdepan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penjurusan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karier_terdepan.jurusan",
                    ),
                ),
                (
                    "minat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karier_terdepan.minat",
                    ),
                ),
                (
                    "tes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="karier_terdepan.tes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penjurusan_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
