# Generated by Django 5.0 on 2023-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karier_terdepan", "0002_penjurusan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penjurusan",
            name="jurusan",
            field=models.TextField(),
        ),
    ]
